admin_index:
    path: /admin
    controller: App\Controller\Admin\HomeController::index
admin_category_index:
    path: /admin/categories
    controller: App\Controller\Admin\CategoryController::index
admin_category_create:
    path: /admin/categories/create
    controller: App\Controller\Admin\CategoryController::create
admin_settings_index:
    path: /admin/settings
    controller: App\Controller\Admin\SettingsController::index
admin_settings_create:
    path: /admin/settings/create
    controller: App\Controller\Admin\SettingsController::create
admin_settings_update:
    path: /admin/settings/update
    controller: App\Controller\Admin\SettingsController::update
admin_settings_delete:
    path: /admin/settings/delete
    controller: App\Controller\Admin\SettingsController::delete
front_help:
    path: /front/help
    controller: App\Controller\FrontController::help
front_help_item:
    path: /front/help/item-{template}
    controller: App\Controller\FrontController::item
